### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by hades200082** [rshackleton/gatsby-packages#115]
**Describe the bug**
This plugin doesn't seem to do anything.

The `fluid` and `fixed` properties fail to appear in GraphiQL and if I try to use them in my project I get `Cannot query field "fluid" on type "kontent_item_asset_element".`

**To Reproduce**

My plugins array in gatsby-config.js:

```js
  plugins: [
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: '@kentico/gatsby-source-kontent',
      options: {
        projectId: process.env.KONTENT_PROJECT_ID,
        globalQueryConfig: {
          usePreviewMode: !!process.env.KONTENT_PREVIEW_KEY
        },
        previewApiKey: process.env.KONTENT_PREVIEW_KEY,
        languageCodenames: [
          'en-GB', 'es-ES'
        ],
      }
    },
    {
      resolve: `@rshackleton/gatsby-transformer-kontent-image`,
      options: {},
    },
  ],
```

**Expected behavior**
The plugin should work.

**Packages**

- "@kentico/gatsby-source-kontent": "^6.0.0",
- "@rshackleton/gatsby-transformer-kontent-image": "^0.1.0",
- "gatsby-image": "^2.4.3",
- "gatsby-plugin-sharp": "^2.6.3",
- "gatsby-transformer-sharp": "^2.5.2",

**Comment by rshackleton** [comment]
@hades200082 the plugin has not yet been updated for the new v6 source plugin, I'll aim to have that done this weekend.

**Comment by vit-svoboda** [comment]
Meanwhile, I was able to work around that (or perhaps hack around would be more fitting) by adding the following code in my `gatsby-node.js`
```
const {
  fixedResolver,
  fluidResolver,
  resizeResolver,
} = require ('@rshackleton/gatsby-transformer-kontent-image/src/resolvers');

exports.createResolvers = ({ createResolvers }) => {
  createResolvers({
    kontent_item_asset_element: {
      fixed: fixedResolver,
      fluid: fluidResolver,
      resize: resizeResolver,
    }
  });
};
```
The issue is just the KontentItemAssetElement name change in v6 source plugin.

**Comment by hades200082** [comment]
That's great, thanks.

**Comment by rshackleton** [comment]
I've started working on an update to fix this but there is an issue with v6 that will be a blocker for now.

https://github.com/Kentico/kontent-gatsby-packages/issues/143

Once that's resolved I'll push out a new version; the workaround provided by @vit-svoboda will add support for standard asset fields but you will have issues with assets in rich text fields.

I would recommend sticking to v5 if you wish to use this plugin until the above issue is resolved.

**Comment by rshackleton** [comment]
Ignore, turns out it was an issue with the gatsby cache. 🙈

`gatsby clean` to the rescue...

**Comment by rshackleton** [comment]
Fixed in v1.0.0

**Comment by hades200082** [comment]
Great job. Tested and working in my project. Fantastic speed of support.

This package is what Kentico are missing from their own packages for Kontent IMO

**Comment by rshackleton** [comment]
@hades200082 just wanted to give you a heads up to upgrade to v2.0.0 with the latest source plugin (v6.0.1).

**Comment by hades200082** [comment]
Thanks for the update... will do.
